// Exportar componentes comunes
export { default as ErrorBoundary } from './ErrorBoundary.jsx';
export { default as AppLoadingScreen, APP_LOADING_BG } from './AppLoadingScreen.jsx';
export { default as GoogleLoader } from './GoogleLoader.jsx';
export { default as CommonActions } from './CommonActions.jsx';
export { default as CommonConstruction } from './CommonConstruction.jsx';
export { default as CommonDate } from './CommonDate.jsx';
export { default as CommonDetails } from './CommonDetails.jsx';
export { default as CommonField } from './CommonField.jsx';
export { default as CommonForm } from './CommonForm.jsx';
export { default as CommonGrid } from './CommonGrid.jsx';
export { default as CommonHeader } from './CommonHeader.jsx';
export { default as CommonProgressBar } from './CommonProgressBar.jsx';
export { default as DynamicIcon } from './DynamicIcon.jsx';
export { default as EmptyState } from './EmptyState.jsx';
export { default as EstadoIcon } from './EstadoIcon.jsx';
export { default as PageContainer } from './PageContainer.jsx';
export { default as CollapseChevron } from './CollapseChevron.jsx';
export { default as CollapseSectionToggle } from './CollapseSectionToggle.jsx';
export { default as SystemButtons } from './SystemButtons.jsx';
export { ACTIONS, getStandardActions } from './CommonActions.jsx';
export { default as HabitCrudActions } from './HabitCrudActions.jsx';
export { HabitCounterBadge } from './HabitCounterBadge.jsx';
export { PwaInstallBanner, DesktopAppsSection } from '../pwa/index.js';
export { ToolbarAddButton, TOOLBAR_ICON_BUTTON_SX } from './ToolbarAddButton.jsx';
export * from './snackbarUtils.jsx';
export * from './StatusSystem.js';
export * from './CommonFormStyles.jsx';