// Exportar hooks personalizados (usar named exports cuando corresponde)
export { default as useHabitsPreferences, invalidateHabitsPreferencesCache, setHabitsPreferencesCache, setHabitChainsCache, getCachedHabitChains, updateHabitChainsOnApi } from './useHabitsPreferences.js';
export * from './useActionHistory.js';
export * from './useAPI.js';
export * from './useAppDetection.js';
export * from './useContratoData.js';
export * from './useContratoExpansion.js';
export * from './useCuotaGuardado.js';
export { default as useDebounce } from './useDebounce.js';
export * from './useDocumentosPropiedad.js';
export * from './useScopedUndo.js';
export * from './useLocalPreservationState.js';
export * from './useMercadoPago.js';
export * from './useOptimisticUpdate.js';
export * from './usePerformanceOptimizer.js';
export * from './usePropiedadDatos.js';
export * from './useRelationalData.js';
export { default as useResponsive } from './useResponsive.js';
export { default as useHorizontalDragScroll } from './useHorizontalDragScroll.js';
export { default as useHabitGroupContextMenu } from './useHabitGroupContextMenu.js';
export { useHabitSectionCreateOption, HABIT_SECTION_CREATE_LABEL } from './useHabitSectionCreateOption.js';
export { useHabitRoutineCreateOption } from './useHabitRoutineCreateOption.js';
export { default as useRoutineAssignment } from '../habits/routines/useRoutineAssignment.js';
export { default as usePwaInstall, isStandalonePwa, isPwaInstallDismissed, dismissPwaInstall } from './usePwaInstall.js';
export * from './useStatusOptimizer.js';
export * from './useTimezone.js';