import {
  AddOutlined,
  AttachFileOutlined,
  CheckCircleOutlined,
  ChecklistOutlined,
  Close,
  EventAvailableOutlined,
  EventNoteOutlined,
  InterestsOutlined,
  LabelOutlined,
  NotesOutlined,
  PersonAddOutlined,
  PriorityHigh,
  TimerOutlined,
  TrackChangesOutlined,
  LinearScaleOutlined,
} from '@mui/icons-material';
import { getIconByKey } from '@shared/navigation/menuIcons';

/** Iconos centralizados para formularios de tarea (alineados con menuIcons). */
export const TareaFormIcons = {
  schedule: getIconByKey('calendarToday'),
  calendar: getIconByKey('calendarToday'),
  duration: TimerOutlined,
  deadline: EventAvailableOutlined,
  description: NotesOutlined,
  notes: NotesOutlined,
  proyecto: getIconByKey('objetivo'),
  objetivo: getIconByKey('objetivo'),
  subtarea: ChecklistOutlined,
  estado: LabelOutlined,
  owners: PersonAddOutlined,
  prioridad: PriorityHigh,
  habit: EventNoteOutlined,
  habitIcon: InterestsOutlined,
  recurrence: TrackChangesOutlined,
  add: AddOutlined,
  close: Close,
  completed: CheckCircleOutlined,
  attach: AttachFileOutlined,
  folder: getIconByKey('folder'),
  rutina: LinearScaleOutlined,
};
